# Generated by Django 5.2.6 on 2025-09-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newitem_created_newitem_updated_alter_newitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='newitem',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
