# Generated by Django 5.2.6 on 2025-09-23 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_categories_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newitem', to='core.categories'),
        ),
    ]
