# Generated by Django 5.2.6 on 2025-09-24 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_newitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
